# Site settings
title: OpenBroadcaster Player
tagline: A performant and responsive media streamer 
email: openbroadcaster@openbroadcaster.com
description: > # this means to ignore newlines until "baseurl"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Player/" # the subpath of your site, e.g. /blog/
url: "http://openbroadcaster.github.io/Player" # the base hostname & protocol for your site
twitter_username: openbroadcaster
github_username:  openbroadcaster
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

# Gems
gems: [jekyll-paginate]
